/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_idea_net_TunTap */

#ifndef _Included_org_idea_net_TunTap
#define _Included_org_idea_net_TunTap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_idea_net_TunTap
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_idea_net_TunTap_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_idea_net_TunTap
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_idea_net_TunTap_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_idea_net_TunTap
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_idea_net_TunTap_write
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_idea_net_TunTap
 * Method:    await
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_idea_net_TunTap_await
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_idea_net_TunTap
 * Method:    read
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_idea_net_TunTap_read
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
